@echo off
echo Starting TruthLens Fake News Detector...
echo.
echo Ensuring dependencies are installed...
pip install flask scikit-learn nltk pandas
echo.
echo Checking for trained model...
if not exist "models\final_model.pkl" (
    echo Model not found. Training model now...
    python src\train.py
)
echo.
echo Launching Application...
start http://127.0.0.1:5000
python app.py
pause
